=== nejcjakic/goalball-score-sheet/src/data/dataUpdateSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  targetNamespace="http://www.goalballschoresheet.com/schemas/dataUpdateSchema"
  xmlns="http://www.goalballschoresheet.com/schemas/dataUpdateSchema"
  elementFormDefault="qualified">

  <xsd:element name="updateData">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="listOfOfficials" type="listOfOfficialsType" />
        <xsd:element name="listOfTeams" type="listOfTeamsType" />
      </xsd:sequence>
      <xsd:attribute name="date" type="xsd:date" />
    </xsd:complexType>
  </xsd:element>

  <xsd:complexType name="listOfOfficialsType">
    <xsd:sequence>
      <xsd:element name="official" type="officialType"
        minOccurs="0" maxOccurs="unbounded" />
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="listOfTeamsType">
    <xsd:sequence>
      <xsd:element name="team" type="teamType" minOccurs="0"
        maxOccurs="unbounded" />
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="officialType">
    <xsd:sequence>
      <xsd:element name="lastName" type="xsd:string" />
      <xsd:element name="firstName" type="xsd:string" />
      <xsd:element name="gender" type="xsd:string" />
      <xsd:element name="officialLevel" type="officialLevel" />
      <xsd:element name="country" type="xsd:string" />
    </xsd:sequence>
  </xsd:complexType>


  <xsd:complexType name="teamType">
    <xsd:sequence>
      <xsd:element name="staff" type="staffType" minOccurs="0"
        maxOccurs="unbounded" />
      <xsd:element name="player" type="playerType"
        minOccurs="0" maxOccurs="unbounded" />
    </xsd:sequence>
    <xsd:attribute name="teamName" type="xsd:string" use="required" />
    <xsd:attribute name="country" type="xsd:string" use="required" />
    <xsd:attribute name="nationalTeam" type="xsd:boolean"
      use="required" />
  </xsd:complexType>

  <xsd:complexType name="staffType">
    <xsd:sequence>
      <xsd:element name="lastName" type="xsd:string" />
      <xsd:element name="firstName" type="xsd:string" />
      <xsd:element name="personPosition" type="xsd:string" />
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="playerType">
    <xsd:sequence>
      <xsd:element name="lastName" type="xsd:string" />
      <xsd:element name="firstName" type="xsd:string" />
    </xsd:sequence>
  </xsd:complexType>

  <xsd:simpleType name="officialLevel">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="ITO" />
      <xsd:enumeration value="National" />
      <xsd:enumeration value="Level I" />
      <xsd:enumeration value="Level II" />
      <xsd:enumeration value="Level III" />
    </xsd:restriction>
  </xsd:simpleType>
</xsd:schema>

=== nejcjakic/goalball-score-sheet/src/data/initialData.xml
<?xml version="1.0" encoding="UTF-8"?>
<updateData date="2001-01-01"
  xmlns="http://www.goalballschoresheet.com/schemas/dataUpdateSchema"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.goalballschoresheet.com/schemas/dataUpdateSchema dataUpdateSchema.xsd ">
  <listOfOfficials>
    <official>
      <lastName>Jakic</lastName>
      <firstName>Nejc</firstName>
      <gender>male</gender>
      <officialLevel>Level III</officialLevel>
      <country>Slovenia</country>
    </official>
    <official>
      <lastName>Fras</lastName>
      <firstName>Patricia</firstName>
      <gender>female</gender>
      <officialLevel>Level III</officialLevel>
      <country>Slovenia</country>
    </official>
    <official>
      <lastName>Fras</lastName>
      <firstName>Bojana</firstName>
      <gender>female</gender>
      <officialLevel>Level II</officialLevel>
      <country>Slovenia</country>
    </official>
    <official>
      <lastName>Strancar</lastName>
      <firstName>Dolores</firstName>
      <gender>female</gender>
      <officialLevel>Level I</officialLevel>
      <country>Slovenia</country>
    </official>
    <official>
      <lastName>More</lastName>
      <firstName>Erlend</firstName>
      <gender>male</gender>
      <officialLevel>National</officialLevel>
      <country>Slovenia</country>
    </official>
    <official>
      <lastName>Gjura</lastName>
      <firstName>Natasa</firstName>
      <gender>female</gender>
      <officialLevel>ITO</officialLevel>
      <country>Slovenia</country>
    </official>
    <official>
      <lastName>Brezovar</lastName>
      <firstName>Miha</firstName>
      <gender>male</gender>
      <officialLevel>ITO</officialLevel>
      <country>Canada</country>
    </official>
  </listOfOfficials>
  <listOfTeams>
    <team teamName="Slovenia" country="Slovenia" nationalTeam="true">
      <staff>
        <lastName>Trenerko</lastName>
        <firstName>Trener</firstName>
        <personPosition>Coach</personPosition>
      </staff>
      <staff>
        <lastName>Maserko</lastName>
        <firstName>Maser</firstName>
        <personPosition>Physio</personPosition>
      </staff>
      <staff>
        <lastName>Terapevtko</lastName>
        <firstName>Terapevt</firstName>
        <personPosition>Therapist</personPosition>
      </staff>
      <player>
        <lastName>Novak</lastName>
        <firstName>Janez</firstName>
      </player>
      <player>
        <lastName>Zidar</lastName>
        <firstName>Joze</firstName>
      </player>
      <player>
        <lastName>Cevljar</lastName>
        <firstName>Marko</firstName>
      </player>
    </team>
    <team teamName="Canada" country="Canada" nationalTeam="true">
      <staff>
        <lastName>McCoach</lastName>
        <firstName>Coach</firstName>
        <personPosition>Coach</personPosition>
      </staff>
      <staff>
        <lastName>McTherapist</lastName>
        <firstName>Therapist</firstName>
        <personPosition>Therapist</personPosition>
      </staff>
      <player>
        <lastName>Doe</lastName>
        <firstName>John</firstName>
      </player>
      <player>
        <lastName>Maverick</lastName>
        <firstName>Carter</firstName>
      </player>
      <player>
        <lastName>Cruise</lastName>
        <firstName>Tom</firstName>
      </player>
    </team>
    <team teamName="Zolne" country="Slovenia" nationalTeam="false">
      <player>
        <lastName>Ledinek</lastName>
        <firstName>Matej</firstName>
      </player>
      <player>
        <lastName>Pirc</lastName>
        <firstName>Dejan</firstName>
      </player>
    </team>
  </listOfTeams>
</updateData>
